name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    name: Test on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    env:
      # Make sure CI fails on all warnings, including Clippy lints
      RUSTFLAGS: "-Dwarnings"
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
      fail-fast: false

    steps:
      - uses: actions/checkout@v4

      - name: Lint
        run: cargo clippy --all-targets

      - name: Build
        run: cargo build
        
      - name: Run tests
        run: cargo test --verbose

  test-android:
    name: Test on Android (aarch64)
    runs-on: ubuntu-latest
    env:
      CROSS_VERSION: v0.2.5

    steps:
      - uses: actions/checkout@v4

      - name: Setup cache
        uses: Swatinem/rust-cache@v2
      
      - name: Install cross
        run: |
          cargo install cross --git https://github.com/cross-rs/cross --rev "$CROSS_VERSION" --force

      - name: Build
        run: |
          cross build --verbose --target aarch64-linux-android

      - name: Run tests
        run: |
          cross test --verbose --target aarch64-linux-android