name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    name: Test on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
      fail-fast: false

    steps:
      - uses: actions/checkout@v3
      
      - name: Build
        run: cargo build
        
      - name: Run tests
        run: cargo test --verbose

  # TODO: find a way to fix this https://github.com/evilsocket/legba/actions/runs/17064881715/job/48379641330
  # 
  # test-android:
  #   name: Test on Android (aarch64)
  #   runs-on: ubuntu-latest

  #   steps:
  #     - uses: actions/checkout@v3
  #     
  #     - name: Build binary
  #       uses: houseabsolute/actions-rust-cross@v1
  #       with:
  #         command: test
  #         target: aarch64-linux-android
  #         args: --verbose
