name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always
# Make sure CI fails on all warnings, including Clippy lints
  RUSTFLAGS: "-Dwarnings"

jobs:
  test:
    name: Test on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
      fail-fast: false

    steps:
      - uses: actions/checkout@v3

      - name: Lint
        # somehow on windows this errors with:
        # error: failed to run custom build command for `sibyl v0.6.19`
        # Caused by:
        #   process didn't exit successfully: `D:\a\legba\legba\target\debug\build\sibyl-8bb2dd83cace707f\build-script-build` (exit code: 1)
        #   --- stderr
        #   OCI_LIB_DIR must be specified for "msvc" targets
        if: matrix.os != 'windows-latest'
        run: cargo clippy --all-targets --all-features

      - name: Build
        run: cargo build
        
      - name: Run tests
        run: cargo test --verbose

  # TODO: find a way to fix this https://github.com/evilsocket/legba/actions/runs/17064881715/job/48379641330
  # 
  # test-android:
  #   name: Test on Android (aarch64)
  #   runs-on: ubuntu-latest

  #   steps:
  #     - uses: actions/checkout@v3
  #     
  #     - name: Build binary
  #       uses: houseabsolute/actions-rust-cross@v1
  #       with:
  #         command: test
  #         target: aarch64-linux-android
  #         args: --verbose
