name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always
# Make sure CI fails on all warnings, including Clippy lints
  RUSTFLAGS: "-Dwarnings"

jobs:
  test:
    name: Test on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
      fail-fast: false

    steps:
      - uses: actions/checkout@v4

      - name: Lint
        # somehow on windows this errors with:
        # error: failed to run custom build command for `sibyl v0.6.19`
        # Caused by:
        #   process didn't exit successfully: `D:\a\legba\legba\target\debug\build\sibyl-8bb2dd83cace707f\build-script-build` (exit code: 1)
        #   --- stderr
        #   OCI_LIB_DIR must be specified for "msvc" targets
        if: matrix.os != 'windows-latest'
        run: cargo clippy --all-targets --all-features

      - name: Build
        run: cargo build
        
      - name: Run tests
        run: cargo test --verbose

  test-android:
    name: Test on Android (aarch64)
    runs-on: ubuntu-latest
    env:
      CROSS_VERSION: v0.2.5

    steps:
      - uses: actions/checkout@v4

      - name: Setup cache
        uses: Swatinem/rust-cache@v2
      
      - name: Install cross
        run: |
          cargo install cross --git https://github.com/cross-rs/cross --rev "$CROSS_VERSION" --force

      - name: Build
        run: |
          cross build --verbose --target aarch64-linux-android

      - name: Run tests
        run: |
          cross test --verbose --target aarch64-linux-android