name: release

on:
  push:
    tags:
      - "v*"
  # REMOVE THIS WHEN READY
  workflow_dispatch:

permissions:
  contents: write

jobs:
  create-release:
    name: create-release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Get the release version from the tag
        if: env.VERSION == ''
        # UNCOMMENT WHEN READY
        # run: echo "VERSION=${{ github.ref_name }}" >> $GITHUB_ENV
        run: echo "VERSION=v0.0.1" >> $GITHUB_ENV
      - name: Show the version
        run: |
          echo "version is: $VERSION"
      # UNCOMMENT WHEN READY
      # - name: Check that tag version and Cargo.toml version are the same
      #   run: |
      #     if ! grep -q "version = \"$VERSION\"" Cargo.toml; then
      #       echo "version does not match Cargo.toml" >&2
      #       exit 1
      #     fi
          
      # - name: Create GitHub release
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #   run: gh release create $VERSION --draft --verify-tag --title $VERSION
      - name: Create GitHub release mock
        run: echo gh release create $VERSION --draft --verify-tag --title $VERSION
    outputs:
      version: ${{ env.VERSION }}

  build-release:
    name: build-release
    needs: ['create-release']
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        - name: linux-x86_64
          os: ubuntu-latest
          bin_name: legba

        - name: apple-darwin-arm64
          os: macos-latest
          bin_name: legba

        - name: windows-x86_64
          os: windows-latest
          bin_name: legba.exe

      fail-fast: false

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Build release binary
      run: |
        cargo build --verbose --release

    - name: Set binary name
      run: |
        echo "BIN=target/release/${{ matrix.bin_name }}" >> $GITHUB_ENV

    - name: Determine archive name
      shell: bash
      run: |
        version="${{ needs.create-release.outputs.version }}"
        echo "ARCHIVE=legba-$version-${{ matrix.name }}" >> $GITHUB_ENV

    - name: Show binary info
      shell: bash
      run: |
        file "$BIN"

    - name: Creating directory for archive
      run: |
        mkdir -p "$ARCHIVE"
        cp "$BIN" "$ARCHIVE"/
        cp -rf {README.md,LICENSE,docs} "$ARCHIVE"/

    - name: Build archive (Windows)
      if: matrix.os == 'windows-latest'
      run: |
        7z a "$ARCHIVE.zip" "$ARCHIVE"
        certutil -hashfile "$ARCHIVE.zip" SHA256 > "$ARCHIVE.zip.sha256"
        echo "ASSET=$ARCHIVE.zip" >> $GITHUB_ENV
        echo "ASSET_SUM=$ARCHIVE.zip.sha256" >> $GITHUB_ENV

    - name: Build archive (Unix)
      if: matrix.os != 'windows-latest'
      run: |
        tar czf "$ARCHIVE.tar.gz" "$ARCHIVE"
        shasum -a 256 "$ARCHIVE.tar.gz" > "$ARCHIVE.tar.gz.sha256"
        echo "ASSET=$ARCHIVE.tar.gz" >> $GITHUB_ENV
        echo "ASSET_SUM=$ARCHIVE.tar.gz.sha256" >> $GITHUB_ENV

    - name: Upload mock
      run: |
        version="${{ needs.create-release.outputs.version }}"
        echo gh release upload "$version" ${{ env.ASSET }} ${{ env.ASSET_SUM }}

    # UNCOMMENT WHEN READY
    # - name: Upload release archive
    #   env:
    #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    #   run: |
    #     version="${{ needs.create-release.outputs.version }}"
    #     gh release upload "$version" ${{ env.ASSET }} ${{ env.ASSET_SUM }}

  build-release-deb:
    name: build-release-deb
    needs: ['create-release']
    runs-on: ubuntu-latest
    env:
      RUST_BACKTRACE: 1

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install packages (Ubuntu)
      run: |
        .github/workflows/ubuntu-install-packages

    - name: Install cargo-deb
      run: |
        cargo install cargo-deb

    - name: Create deployment directory
      run: |
        dir=deployment/deb
        mkdir -p "$dir"
        echo "DEPLOY_DIR=$dir" >> $GITHUB_ENV

    - name: Build release binary
      run: |
        cargo deb --profile deb
        version="${{ needs.create-release.outputs.version }}"
        echo "DEB_DIR=target/debian" >> $GITHUB_ENV
        echo "DEB_NAME=legba_$version-1_amd64.deb" >> $GITHUB_ENV

    - name: Create sha256 sum of deb file
      run: |
        ls -la "$DEB_DIR"
        cd "$DEB_DIR"
        sum="$DEB_NAME.sha256"
        shasum -a 256 "$DEB_NAME" > "$sum"
        echo "SUM=$sum" >> $GITHUB_ENV

    - name: Upload mock
      run: |
        cd "$DEB_DIR"
        version="${{ needs.create-release.outputs.version }}"
        echo gh release upload "$version" "$DEB_NAME" "$SUM"

    # UNCOMMENT WHEN READY
    # - name: Upload release archive
    #   env:
    #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    #   run: |
    #     cd "$DEB_DIR"
    #     version="${{ needs.create-release.outputs.version }}"
    #     gh release upload "$version" "$DEB_NAME" "$SUM"