name: macOS tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: macos-latest
    strategy:
        matrix:
          os: [macos-latest]

    steps:
        - name: Install deps
          # https://stackoverflow.com/questions/52921122/homebrew-install-specific-version-of-formula
          # with fix https://github.com/jhen0409/react-native-debugger/issues/567 
          run: wget https://raw.githubusercontent.com/Homebrew/homebrew-core/764f3e71a50bcc86ea9821b62cd58d7c0862f1a9/Formula/s/samba.rb && brew install --HEAD -s samba.rb
        - name: Fix samba dep
          # https://github.com/evilsocket/legba/issues/40   
          run: ln -s /opt/homebrew/Cellar/samba/4.20.4/lib/libsmbclient.dylib /opt/homebrew/Cellar/samba/4.20.4/lib/libsmbclient.inst.dylib
        - uses: actions/checkout@v3
        - name: Build
          run: cargo build --verbose
        - name: Run tests
          run: cargo test --verbose
