name: macOS tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: macos-latest
    strategy:
        matrix:
          os: [macos-latest]

    steps:
        - name: Install deps
          run: brew update && brew install samba
        - name: Fix samba dep
          # https://github.com/evilsocket/legba/issues/40
          run: ln -s /opt/homebrew/Cellar/samba/4.20.0/lib/libsmbclient.dylib /opt/homebrew/Cellar/samba/4.20.0/lib/libsmbclient.inst.dylib
        - uses: actions/checkout@v3
        - name: Build
          run: cargo build --verbose
        - name: Run tests
          run: cargo test --verbose
